name: Template
on:
  push:
    branches:
      - main
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'gatling-java-example'
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4
      - name: Prepare
        run: |
          export LC_CTYPE=C
          export LANG=C

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo ${GITHUB_ACTOR} | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo ${NAME} | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.${SAFE_ACTOR}.${SAFE_NAME}"

          echo "Using GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "Using GITHUB_ACTOR=${GITHUB_ACTOR}"
          echo "Using NAME=${NAME}"
          echo "Using GROUP=${GROUP}"

          # Replace placeholders in the template-files files
          sed -i "s/%NAME%/${NAME}/g" .github/template-files/*
          sed -i "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-files/*
          sed -i "s/%GROUP%/${GROUP}/g" .github/template-files/*

          # Update package references in sources
          find src -type f -exec sed -i "s/gatling.test.example/${GROUP}/g" {} +

          # Update K8s deployment files
          find deployment -type f -exec sed -i "s/gatling-java-example/${NAME}/g" {} +
          find deployment -type f -exec sed -i "s/gatling.test.example/${GROUP}/g" {} +
          find deployment -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          # Update shell scripts
          find . -name "*.sh" -type f -exec sed -i "s/gatling-java-example/${NAME}/g" {} +
          find . -name "*.sh" -type f -exec sed -i "s/gatling.test.example/${GROUP}/g" {} +
          find . -name "*.sh" -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          # Update Makefile
          find . -name Makefile -type f -exec sed -i "s/gatling-java-example/${NAME}/g" {} +
          find . -name Makefile -type f -exec sed -i "s/gatling.test.example/${GROUP}/g" {} +
          find . -name Makefile -type f -exec sed -i "s/jecklgamis/${ACTOR}/g" {} +

          # Update pom.xml
          find . -name pom.xml -type f -exec sed -i "s/gatling-java-example/${NAME}/g" {} +
          find . -name pom.xml -type f -exec sed -i "s/gatling.test.example/${GROUP}/g" {} +
          find . -name pom.xml -type f -exec sed -i "s/com.jecklgamis/${GROUP}/g" {} +

          # Update Dockerfile
          find . -name Dockerfile -type f -exec sed -i "s/gatling-java-example/${NAME}/g" {} +
          find . -name Dockerfile -type f -exec sed -i "s/Jerrico Gamis/FirstName LastName/g" {} +
          find . -name Dockerfile -type f -exec sed -i "s/jecklgamis@gmail.com/user@some-domain/g" {} +

          # Copy content
          mkdir -p src/main/java/${GROUP//.//}
          cp -R .github/template-files/* .
          cp -R src/main/java/gatling/test/example/* src/main/java/${GROUP//.//}/

          # Clean up
          rm -rf \
            .circleci \
            .github/readme \
            .github/template-files \
            .github/workflows/template.yml \
            .idea/icon.png \
            src/main/java/gatling \
            LICENSE \
            package-artifacts.sh \
            submit*.sh \
            k8s-job-demo.gif
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
